### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by mfaerevaag** [macgeiger/bitsee#1]
Hi!

I about to try reversing the QMGR format, so I can parse `qmgr{0,1}.dat`, but I thought I would ask if you had any luck before I started.

I found this repo through one of your articles on malware through BITS.

If not, ignore this issue 👍

**Comment by danzek** [comment]
See https://github.com/ANSSI-FR/bits_parser

**Comment by macgeiger** [comment]
Nice work. The README now points to the ANSSI repo.
